# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Fatal-Exception
version:      0.02
version_from: lib/Fatal/Exception.pm
installdirs:  site
requires:
    Exception::Base:               0.12
    Exception::System:             0.07
    Test::Unit::Lite:              0.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
