--- #YAML:1.0
name: Fatal-Exception
abstract: Succeed or throw exception
version: 0.0101
author:
  - Piotr Roszatycki <dexter@debian.org>
license: perl
distribution_type: module
requires:
  perl: 5.006
  Exception::Base: 0.07
  Exception::System: 0.06
build_requires:
  Test::Unit::Lite: 0
urls:
  license: http://dev.perl.org/licenses/
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Piotr Roszatycki <dexter@debian.org>
