---
name: Fatal-Exception
version: 0.04
author:
  - 'Piotr Roszatycki <dexter@debian.org>'
abstract: succeed or throw exception
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exception::Base: 0.21
  perl: 5.006
build_requires:
  Test::Assert: 0
  Test::Unit::Lite: 0.07
provides:
  Exception::Argument:
    file: lib/Exception/Argument.pm
    version: 0.04
  Exception::Fatal:
    file: lib/Exception/Fatal.pm
    version: 0.04
  Fatal::Exception:
    file: lib/Fatal/Exception.pm
    version: 0.04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
